### ISSUE TITLE
Readme file not reflecting the actual repo structure+impossible to run brski command using the dev-config.ini

### ISSUE THREAD

**Issue by marcoCalipari** [nqminds/brski#11] opened 2023-05-19 15:43 UTC
## Problem ##

According to the tutorial, I should be supposed to be able to run the brski command with a configuration file with the command:

`./build/src/brski -c ./build/dev-config.ini` 

However there are a couple of issue with this:

1. The path described in this line are not the same as the ones that actually appears after the building process if using the presets. Specifically, the sturcutre will look as follow:

```powershell
tree -d ./
./
├── build
│   ├── dl
│   └── linux

``` 
There are two additional folders. It is not a big deal, just confusing and a little fix that can make the user experience a little more smooth.

2.  Still on this command ``./build/src/brski -c ./build/dev-config.ini``, although is changed the paths to the correct one there is a discrepanncy. Specifically the `dev-config.ini` is not present in the build direcotry:
![image](https://github.com/nqminds/brski/assets/48682055/d5bf62af-9822-417a-bb7f-d362ff78ed3e)

## What I tried to do ##

Although in the wrong places, I was able to locate the `dev-config.ini` file in the path `…/build/linux/src/brski`
Then, from the same brski folder I tried to run the command: `brski -c ./dev-config.ini`.
This created the following output:

```shell
└─$ brski -c ./dev-config.ini 
Command-line usage error: Unrecognized command "(null)"
``` 

I even tried from different locations and using the correct path, however I got always the same error.
Is there a reason why this happens? the building and installation process went fine.
Is there anything that I missed during the installation process?

Thanks in advance for your time 

## Setup ##
Kali linux with zsh terminal
Same problem even in bash

**Comment by aloisklink** [comment] 2023-06-06 10:08
Hi @marcoCalipari,

I'm not on an expert on this repo (today is the first time I've looked at this code!), but it looks like the `brski` executable requires a `<command>` argument.

From the `-h` output:

```console
user@pc:~/brski (fix/https_server-nondeclared-context)$ ./build/src/brski/brski -h
brski version 0.2.0-alpha.0
Usage:
	brski [-c filename] [-o filename] [-d] [-h] [-v] <command>

NquiringMinds BRSKI protocol tool.

Show, export and manipulate vouchers. Create registrar and MASA servers.

Commands:
	epvr		Export the pledge voucher request as base64 CMS file
	preq		Send a pledge-voucher request to the registrar
	registrar	Starts the registrar
	masa		Starts the MASA

Options:
	-c filename	 Path to the config file
	-o filename	 Path to the exported file
	-d		 Verbosity level (use multiple -dd... to increase verbosity)
	-h		 Show help
	-v		 Show app version

Copyright Nquiringminds Ltd
```

Although, I'm not sure what any of the commands actually do (but unlike @mereacre, I'm not an expert on the BRSKI RFC).

I'm trying to get the brski command working on my own computer today, so if I figure it out, I'll try to make a PR that contains some better docs.

**Comment by marcoCalipari** [comment] 2023-06-06 11:23
Hi @aloisklink 

You were right, it was expecting a command, thanks a lot for your help.
In case you manage to have a working example, would you mind adding it to the documentation? I am also struggling trying to understand how it works.

Thanks, cheers

**Comment by mereacre** [comment] 2023-06-06 18:18
@marcoCalipari Please check the usage examples https://github.com/nqminds/brski/blob/main/docs/usage.md.

**Comment by aloisklink** [comment] 2023-06-13 17:07
> @marcoCalipari Please check the usage examples https://github.com/nqminds/brski/blob/main/docs/usage.md.

I couldn't figure out how to get anything working in the [current `docs/usage.md`](https://github.com/nqminds/brski/blob/02dac8a803153d541915615f412d16b93d4b7732/docs/usage.md) docs.

The problem is, there's no documentation on what the config values do, and how to generate certificates.

In my PR https://github.com/nqminds/brski/pull/26, **I've added some instructions on how to quickly run a MASA/registrar/pledge request using an automatically generated `${CMAKE_BINARY_DIR}/tests/brski/test-config.ini` file.** It's still not ideal, since I'm not really sure how (or if) to generate other certificates, but at least I can get everything running and make a BRSKI pledge request!

Once PR #26 is merged, you should just be able to follow the following steps to run some examples:

https://github.com/nqminds/brski/blob/b541808c3a40acd3f1c56028bded1f358eac7d0e/README.md?plain=1#L123-L146

Ideally, we'd still need:
  - Better documentation, ideally documenting
    - what each `config.ini` param means
    - how to generate/get certificates
  - Better error messages.
    - The BRSKI cli seems to crash whenever anything is wrong, and it doesn't print any error messages. It even exits with exit code 0 (aka SUCCESS) despite crashing. I'm not sure how easy/hard this would be to fix, as the http library BRSKI uses, https://github.com/yhirose/cpp-httplib, doesn't have great logging/error handling capabilities.

**Closed** 2023-06-15 21:39 UTC
